### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Aiolus-X** [Orange-OpenSource/Cool-Chic#3]
Dear author, how to choose the version of cool-chics? I want to train cool-chic v1.

**Comment by theoladune** [comment]
Hi,

There is a few tags indicating the different versions of Cool-chic. The following command clones Cool-chic 1 :

`git clone --branch v1.0 --depth=1 https://github.com/Orange-OpenSource/Cool-Chic.git`

Note that there is a page of the documentation indicating which tag refers to which paper : https://orange-opensource.github.io/Cool-Chic/getting_started/literature.html

Théo

**Comment by Aiolus-X** [comment]
Oh I see, thank you very much!
