### ISSUE TITLE
Regarding decoding, have you considered using a GPU?

### ISSUE THREAD

**Issue by ReBenDish** [Orange-OpenSource/Cool-Chic#8]
We greatly appreciate your company's work, but the model still takes around 800ms for 720p images on Mac or devices without AVX2, which is somewhat slow, especially when considering deployment on mobile devices. Have you considered using a GPU for decoding?

**Comment by theoladune** [comment]
Hi,

I imagine you've measured the runtime when decoding the provided bitstreams. Most of these bitstreams have been obtained using the high-complexity operating point (HOP) described in `cfg/dec/ hop.cfg`, which gives the best compression performance while keeping the MAC / pixel reasonably low.

However, our current decoder implementation is not that optimal for this configuration, as presented in the following [graphs](https://orange-opensource.github.io/Cool-Chic/getting_started/results.html#clic20-pro-valid). Scrolling down a bit to see the BD-rate vs. decoding runtime on CLIC20, we see that the mid-complexity operating point (MOP) is much faster than the HOP (350 ms vs 1050 ms) at the cost of a few additional percents of rate.

So : 

1. If decoding time is an important thing for you, you should use the MOP configuration through `--dec_cfg= cfg/dec/ mop.cfg`
2. Upcoming updates will improve the decoder CPU implementation (regardless of AVX2 availability) yielding significant speed-up
3. GPU implementation on the decoder is not our main priority right now. In fact we'd rather like to show that good decoding speed can be obtained without dedicated hardware such as GPUs.
